// Code generated by promptr; DO NOT EDIT.

package stream

import (
	"context"
	"github.com/zkrebbekx/promptr"
)

type Summary struct {
	Headline string   `json:"headline"`
	Bullets  []string `json:"bullets"`
}

// ClientDefault resolves the "Default" client (with any declared policy) from reg.
func ClientDefault(reg promptr.Registry) promptr.Provider {
	return reg.Get("Default")
}

func SummarizeArticle(ctx context.Context, p promptr.Provider, article string, opt ...promptr.Option) (<-chan promptr.Partial[Summary], error) {
	prompt, err := promptr.Render(`
    Summarize the article as a headline plus bullet points.
    {{ ctx.output_schema }}
    Article: {{ article }}
  `, map[string]any{
		"article": article,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "headline": string // a one-line title
  "bullets": string[]
}`},
	})
	if err != nil {
		var zero <-chan promptr.Partial[Summary]
		return zero, err
	}
	options := promptr.Options{Attempts: 2}
	for _, o := range opt {
		o(&options)
	}
	return promptr.ExtractStream[Summary](ctx, p, prompt, options)
}

func CaptionImage(ctx context.Context, p promptr.Provider, photo promptr.Part, hint string, opt ...promptr.Option) (Summary, error) {
	prompt, err := promptr.Render(`
    Caption the attached image.
    {{ ctx.output_schema }}
    Hint: {{ hint }}
  `, map[string]any{
		"hint": hint,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "headline": string // a one-line title
  "bullets": string[]
}`},
	})
	if err != nil {
		var zero Summary
		return zero, err
	}
	options := promptr.Options{Attempts: 2, UserParts: []promptr.Part{photo}}
	for _, o := range opt {
		o(&options)
	}
	return promptr.Extract[Summary](ctx, p, prompt, options)
}
