// Code generated by promptr; DO NOT EDIT.

package livetest

import (
	"context"
	"testing"

	"github.com/zkrebbekx/promptr"
)

// PromptrProvider is the Provider the generated promptr tests run against.
// Set it (typically in TestMain) to a deterministic provider — providers/fake
// or providers/recorded — or a live one. Tests Skip while it is nil.
var PromptrProvider promptr.Provider

func TestOutage(t *testing.T) {
	if PromptrProvider == nil {
		t.Skip("promptr: set PromptrProvider to run generated tests")
	}
	got, err := ExtractTicket(context.Background(), PromptrProvider, "the production server is DOWN, this is critical!!")
	if err != nil {
		t.Fatalf("ExtractTicket: %v", err)
	}
	if got.Open != true {
		t.Errorf("open = %v, want %v", got.Open, true)
	}
	if got.Severity != SeverityCRITICAL {
		t.Errorf("severity = %v, want %v", got.Severity, SeverityCRITICAL)
	}
	if got.Title != "Server is down" {
		t.Errorf("title = %v, want %v", got.Title, "Server is down")
	}
	if got.Votes != 3 {
		t.Errorf("votes = %v, want %v", got.Votes, 3)
	}
}

func TestSmoke(t *testing.T) {
	if PromptrProvider == nil {
		t.Skip("promptr: set PromptrProvider to run generated tests")
	}
	got, err := ExtractTicket(context.Background(), PromptrProvider, "minor typo on the about page")
	if err != nil {
		t.Fatalf("ExtractTicket: %v", err)
	}
	_ = got
}
