// Code generated by promptr; DO NOT EDIT.

package agent

import (
	"context"
	"encoding/json"
	"github.com/zkrebbekx/promptr"
	"github.com/zkrebbekx/promptr/coerce"
)

type Weather struct {
	City       string `json:"city"`
	Conditions string `json:"conditions"`
	HighC      int    `json:"high_c"`
}

type Flight struct {
	Carrier string `json:"carrier"`
	Price   int    `json:"price"`
}

type Itinerary struct {
	Destination string   `json:"destination"`
	Summary     string   `json:"summary"`
	Packing     []string `json:"packing"`
}

// ClientSmart resolves the "Smart" client (with any declared policy) from reg.
func ClientSmart(reg promptr.Registry) promptr.Provider {
	return reg.Get("Smart")
}

// GetWeatherArgs are the typed arguments for the "GetWeather" tool.
type GetWeatherArgs struct {
	City string `json:"city"`
}

// SearchFlightsArgs are the typed arguments for the "SearchFlights" tool.
type SearchFlightsArgs struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// PlanTripTools holds the Go implementations of the tools PlanTrip may call.
type PlanTripTools struct {
	GetWeather    func(context.Context, GetWeatherArgs) (Weather, error)
	SearchFlights func(context.Context, SearchFlightsArgs) ([]Flight, error)
}

func PlanTrip(ctx context.Context, p promptr.Provider, goal string, tools PlanTripTools) (Itinerary, error) {
	prompt, err := promptr.Render(`
    Plan a trip for this goal, using the tools to check weather and flights.
    {{ ctx.output_schema }}
    Goal: {{ goal }}
  `, map[string]any{
		"goal": goal,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "destination": string
  "summary": string
  "packing": string[]
}`},
	})
	if err != nil {
		var zero Itinerary
		return zero, err
	}
	return promptr.RunTools[Itinerary](ctx, p, prompt, []promptr.Tool{
		{
			Def: promptr.ToolDef{Name: "GetWeather", Description: "Look up the current weather for a city.", Params: `A JSON object with:
{
  "city": string
}`},
			Invoke: func(ctx context.Context, argsJSON string) (string, error) {
				args, err := coerce.Into[GetWeatherArgs](argsJSON)
				if err != nil {
					return "", err
				}
				result, err := tools.GetWeather(ctx, args)
				if err != nil {
					return "", err
				}
				out, err := json.Marshal(result)
				if err != nil {
					return "", err
				}
				return string(out), nil
			},
		},
		{
			Def: promptr.ToolDef{Name: "SearchFlights", Description: "Find available flights between two cities.", Params: `A JSON object with:
{
  "from": string
  "to": string
}`},
			Invoke: func(ctx context.Context, argsJSON string) (string, error) {
				args, err := coerce.Into[SearchFlightsArgs](argsJSON)
				if err != nil {
					return "", err
				}
				result, err := tools.SearchFlights(ctx, args)
				if err != nil {
					return "", err
				}
				out, err := json.Marshal(result)
				if err != nil {
					return "", err
				}
				return string(out), nil
			},
		},
	}, promptr.Options{Attempts: 2})
}
