// Code generated by promptr; DO NOT EDIT.

package validate

import (
	"context"
	"github.com/zkrebbekx/promptr"
	"github.com/zkrebbekx/valx"
)

type Plan string

const (
	PlanFREE       Plan = "FREE"
	PlanPRO        Plan = "PRO"
	PlanENTERPRISE Plan = "ENTERPRISE"
)

// CoerceMembers lets the coerce kernel fuzzy-match model output to a member.
func (Plan) CoerceMembers() []string {
	return []string{"FREE", "PRO", "ENTERPRISE"}
}

type Account struct {
	Email    string `json:"email" valx:"required"`
	Username string `json:"username" valx:"min=3,max=20"`
	Age      int    `json:"age" valx:"gt=0,lt=130" check:"min=18"`
	Plan     Plan   `json:"plan"`
	Seats    int    `json:"seats" check:"min=1,max=100"`
}

// ClientDefault resolves the "Default" client (with any declared policy) from reg.
func ClientDefault(reg promptr.Registry) promptr.Provider {
	return reg.Get("Default")
}

func ExtractAccount(ctx context.Context, p promptr.Provider, text string, opt ...promptr.Option) (Account, error) {
	prompt, err := promptr.Render(`
    Extract an account from the user's message.
    {{ ctx.output_schema }}
    Message: {{ text }}
  `, map[string]any{
		"text": text,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "email": string
  "username": string
  "age": int
  "plan": one of [FREE, PRO, ENTERPRISE]
  "seats": int
}`},
	})
	if err != nil {
		var zero Account
		return zero, err
	}
	options := promptr.Options{Attempts: 2, Validate: func(v any) error { return valx.Validate(v) }, Check: func(v any) error { return valx.ValidateWith(v, "check") }}
	for _, o := range opt {
		o(&options)
	}
	return promptr.Extract[Account](ctx, p, prompt, options)
}
