// Package codegen turns a parsed .promptr File into idiomatic Go source.
//
// Each enum becomes a typed-const set with a coerce.Enum method; each class
// becomes a struct with json tags; each function becomes a Go function whose
// body renders the prompt (with the output schema baked in) and calls
// promptr.Extract to get a typed, parse-repaired result. Output is run through
// go/format so it is gofmt-clean and guaranteed to parse.
package codegen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/zkrebbekx/promptr/dsl"
)

const runtimePkg = "github.com/zkrebbekx/promptr"

// valxPkg is the value-validator generated code imports for @assert/@check rules.
const valxPkg = "github.com/zkrebbekx/valx"

// Generate renders the whole File as a single Go source file in package pkg.
func Generate(pkg string, f *dsl.File) ([]byte, error) {
	desugarInlineUnions(f)
	g := &gen{pkg: pkg, file: f, enums: map[string]dsl.EnumDecl{}, unions: map[string]dsl.UnionDecl{}, tools: map[string]dsl.ToolDecl{}}
	for _, e := range f.Enums {
		g.enums[e.Name] = e
	}
	for _, u := range f.Unions {
		g.unions[u.Name] = u
	}
	for _, t := range f.Tools {
		g.tools[t.Name] = t
	}
	src := g.render()
	out, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("generated code did not format: %w", err)
	}
	return out, nil
}

// desugarInlineUnions rewrites a function whose return type is an inline union
// (`-> A | B`) into a synthesized named union (`<Func>Result`) so the rest of
// codegen has a single, named code path for unions.
func desugarInlineUnions(f *dsl.File) {
	for i := range f.Funcs {
		ret := f.Funcs[i].Ret
		if len(ret.Union) == 0 {
			continue
		}
		name := f.Funcs[i].Name + "Result"
		f.Unions = append(f.Unions, dsl.UnionDecl{Name: name, Variants: ret.Union, Line: f.Funcs[i].Line})
		f.Funcs[i].Ret = dsl.TypeRef{Name: name}
	}
}

type gen struct {
	pkg        string
	file       *dsl.File
	enums      map[string]dsl.EnumDecl
	unions     map[string]dsl.UnionDecl
	tools      map[string]dsl.ToolDecl
	usedCtx    bool
	usedCoerce bool // generated code references the coerce package
	usedJSON   bool // generated code references encoding/json
	usedValx   bool // generated code references the valx validator
}

func (g *gen) render() string {
	var body strings.Builder
	for _, e := range g.file.Enums {
		g.renderEnum(&body, e)
	}
	for _, c := range g.file.Classes {
		g.renderClass(&body, c)
	}
	for _, u := range g.file.Unions {
		g.renderUnion(&body, u)
	}
	for _, c := range g.file.Clients {
		g.renderClient(&body, c)
	}
	for _, t := range g.file.Tools {
		g.renderTool(&body, t)
	}
	for _, fn := range g.file.Funcs {
		g.renderFunc(&body, fn)
	}

	var head strings.Builder
	head.WriteString("// Code generated by promptr; DO NOT EDIT.\n\n")
	head.WriteString("package " + g.pkg + "\n\n")
	if imps := g.imports(); len(imps) > 0 {
		head.WriteString("import (\n")
		for _, imp := range imps {
			head.WriteString("\t" + quote(imp) + "\n")
		}
		head.WriteString(")\n\n")
	}
	return head.String() + body.String()
}

func (g *gen) imports() []string {
	var imps []string
	if g.usedCtx {
		imps = append(imps, "context")
	}
	if g.usedJSON {
		imps = append(imps, "encoding/json")
	}
	if len(g.file.Funcs) > 0 || len(g.file.Clients) > 0 {
		imps = append(imps, runtimePkg)
	}
	if g.usedCoerce {
		imps = append(imps, runtimePkg+"/coerce")
	}
	if g.usedValx {
		imps = append(imps, valxPkg)
	}
	return imps
}

func (g *gen) renderEnum(b *strings.Builder, e dsl.EnumDecl) {
	fmt.Fprintf(b, "type %s string\n\n", e.Name)
	if len(e.Members) > 0 {
		b.WriteString("const (\n")
		for _, m := range e.Members {
			fmt.Fprintf(b, "\t%s%s %s = %q\n", e.Name, m, e.Name, m)
		}
		b.WriteString(")\n\n")
	}
	fmt.Fprintf(b, "// CoerceMembers lets the coerce kernel fuzzy-match model output to a member.\n")
	fmt.Fprintf(b, "func (%s) CoerceMembers() []string {\n\treturn []string{", e.Name)
	for i, m := range e.Members {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", m)
	}
	b.WriteString("}\n}\n\n")
}

func (g *gen) renderClass(b *strings.Builder, c dsl.ClassDecl) {
	fmt.Fprintf(b, "type %s struct {\n", c.Name)
	for _, fld := range c.Fields {
		// @alias renames the wire/json field so the coerce kernel binds the
		// model's output (which the baked schema shows under the alias) to it.
		jsonTag := wireName(fld)
		if fld.Type.Optional {
			jsonTag += ",omitempty"
		}
		// One struct tag carries the json binding plus, when declared, the @assert
		// rules under "valx" (hard) and @check rules under "check" (soft); the
		// generated function feeds these to valx.Validate / valx.ValidateWith.
		parts := []string{fmt.Sprintf("json:%q", jsonTag)}
		if fld.Assert != "" {
			parts = append(parts, fmt.Sprintf("valx:%q", fld.Assert))
		}
		if fld.Check != "" {
			parts = append(parts, fmt.Sprintf("check:%q", fld.Check))
		}
		fmt.Fprintf(b, "\t%s %s `%s`\n", goName(fld.Name), g.goType(fld.Type), strings.Join(parts, " "))
	}
	b.WriteString("}\n\n")
}

// wireName is the json/prompt name for a field: its @alias if set, else its
// declared name.
func wireName(fld dsl.FieldDecl) string {
	if fld.Alias != "" {
		return fld.Alias
	}
	return fld.Name
}

// renderUnion emits a sealed interface for a union plus an unexported marker
// method on each variant, in the spirit of sumx's sealed sum types. coerce
// classifies model output into a variant; the interface makes the set closed
// and exhaustively switchable at the call site.
func (g *gen) renderUnion(b *strings.Builder, u dsl.UnionDecl) {
	marker := "is" + u.Name
	fmt.Fprintf(b, "// %s is a sealed union: one of %s.\n", u.Name, strings.Join(u.Variants, ", "))
	fmt.Fprintf(b, "type %s interface{ %s() }\n\n", u.Name, marker)
	for _, v := range u.Variants {
		fmt.Fprintf(b, "func (%s) %s() {}\n", v, marker)
	}
	b.WriteString("\n")
}

// renderClient emits a constructor that resolves a declared client (and its
// reliability policy) from a promptr.Registry. A plain client is just a lookup;
// a policy client wraps the clients it references with Fallback/RoundRobin/Retry
// — composing the wrappers from policy.go.
func (g *gen) renderClient(b *strings.Builder, c dsl.ClientDecl) {
	expr := g.clientBase(c)
	if c.Policy.Retry > 0 {
		expr = fmt.Sprintf("promptr.Retry(%s, %d, 0)", expr, c.Policy.Retry)
	}
	fmt.Fprintf(b, "// Client%s resolves the %q client (with any declared policy) from reg.\n", c.Name, c.Name)
	fmt.Fprintf(b, "func Client%s(reg promptr.Registry) promptr.Provider {\n\treturn %s\n}\n\n", c.Name, expr)
}

func (g *gen) clientBase(c dsl.ClientDecl) string {
	switch {
	case len(c.Policy.Fallback) > 0:
		return "promptr.Fallback(" + clientRefs(c.Policy.Fallback) + ")"
	case len(c.Policy.RoundRobin) > 0:
		return "promptr.RoundRobin(" + clientRefs(c.Policy.RoundRobin) + ")"
	default:
		return fmt.Sprintf("reg.Get(%q)", c.Name)
	}
}

func clientRefs(names []string) string {
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "Client" + n + "(reg)"
	}
	return strings.Join(parts, ", ")
}

// renderTool emits a tool's typed argument struct. The model's JSON arguments
// are coerced into this struct (in the generated handler wrapper) before the
// user's handler runs.
func (g *gen) renderTool(b *strings.Builder, t dsl.ToolDecl) {
	fmt.Fprintf(b, "// %sArgs are the typed arguments for the %q tool.\n", t.Name, t.Name)
	fmt.Fprintf(b, "type %sArgs struct {\n", t.Name)
	for _, pm := range t.Params {
		tag := pm.Name
		if pm.Type.Optional {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName(pm.Name), g.goType(pm.Type), tag)
	}
	b.WriteString("}\n\n")
}

// toolParamSchema renders the human-readable argument schema baked into the
// tool's ToolDef, in the same style as schemaFor's class shapes.
func (g *gen) toolParamSchema(t dsl.ToolDecl) string {
	if len(t.Params) == 0 {
		return "No arguments."
	}
	var b strings.Builder
	b.WriteString("A JSON object with:\n{\n")
	for _, pm := range t.Params {
		fmt.Fprintf(&b, "  %q: %s%s\n", pm.Name, g.schemaType(pm.Type), optNote(pm.Type))
	}
	b.WriteString("}")
	return b.String()
}

func (g *gen) renderFunc(b *strings.Builder, fn dsl.FuncDecl) {
	g.usedCtx = true
	var partParams []dsl.Param
	params := []string{"ctx context.Context", "p promptr.Provider"}
	for _, pm := range fn.Params {
		params = append(params, fmt.Sprintf("%s %s", pm.Name, g.goType(pm.Type)))
		if isPartType(pm.Type.Name) {
			partParams = append(partParams, pm)
		}
	}
	// A tool-using function takes an extra typed handlers struct and runs the
	// agent loop; emit that struct type first.
	if len(fn.Tools) > 0 {
		g.renderToolHandlers(b, fn)
		params = append(params, "tools "+fn.Name+"Tools")
	}
	// A trailing variadic of functional options lets callers tune retries, a
	// system preamble, or a soft-check sink without the signature changing.
	params = append(params, "opt ...promptr.Option")
	// elem is the coerced value type; retType wraps it in a channel when streaming.
	elem := g.goType(fn.Ret)
	retType := elem
	if fn.Stream {
		retType = "<-chan promptr.Partial[" + elem + "]"
	}
	fmt.Fprintf(b, "func %s(%s) (%s, error) {\n", fn.Name, strings.Join(params, ", "), retType)

	// Render the prompt at runtime so it can use control flow; the output-schema
	// description is still computed at compile time and injected via ctx. Binary
	// part params (image/audio/pdf) are attached to the message, not templated.
	fmt.Fprintf(b, "\tprompt, err := promptr.Render(%s, map[string]any{\n", quote(fn.Prompt))
	for _, pm := range fn.Params {
		if isPartType(pm.Type.Name) {
			continue
		}
		fmt.Fprintf(b, "\t\t%q: %s,\n", pm.Name, pm.Name)
	}
	fmt.Fprintf(b, "\t\t\"ctx\": map[string]any{\"output_schema\": %s},\n", quote(g.schemaFor(fn.Ret)))
	b.WriteString("\t})\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", retType)

	// Build the Options the call uses, then apply any caller-supplied functional
	// options over the top before dispatching.
	opts := g.renderOptions(partParams, fn.Ret)
	fmt.Fprintf(b, "\toptions := %s\n", opts)
	b.WriteString("\tfor _, o := range opt {\n\t\to(&options)\n\t}\n")

	switch {
	case len(fn.Tools) > 0:
		g.renderToolCall(b, fn, elem)
	case g.isUnion(fn.Ret.Name):
		u := g.unions[fn.Ret.Name]
		fmt.Fprintf(b, "\treturn promptr.ExtractUnion[%s](ctx, p, prompt, options, promptr.NewUnion(%s))\n}\n\n", elem, unionSamples(u))
	case fn.Stream:
		fmt.Fprintf(b, "\treturn promptr.ExtractStream[%s](ctx, p, prompt, options)\n}\n\n", elem)
	default:
		fmt.Fprintf(b, "\treturn promptr.Extract[%s](ctx, p, prompt, options)\n}\n\n", elem)
	}
}

// renderToolHandlers emits the `<Func>Tools` struct of typed handler funcs the
// caller supplies — one field per tool the function may call.
func (g *gen) renderToolHandlers(b *strings.Builder, fn dsl.FuncDecl) {
	fmt.Fprintf(b, "// %sTools holds the Go implementations of the tools %s may call.\n", fn.Name, fn.Name)
	fmt.Fprintf(b, "type %sTools struct {\n", fn.Name)
	for _, name := range fn.Tools {
		t, ok := g.tools[name]
		if !ok {
			continue // validated separately; skip so codegen still produces output
		}
		fmt.Fprintf(b, "\t%s func(context.Context, %sArgs) (%s, error)\n", name, name, g.goType(t.Ret))
	}
	b.WriteString("}\n\n")
}

// renderToolCall emits the []promptr.Tool literal (wrapping each typed handler)
// and the RunTools call that drives the agent loop.
func (g *gen) renderToolCall(b *strings.Builder, fn dsl.FuncDecl, elem string) {
	g.usedCoerce = true
	g.usedJSON = true
	b.WriteString("\treturn promptr.RunTools[" + elem + "](ctx, p, prompt, []promptr.Tool{\n")
	for _, name := range fn.Tools {
		t, ok := g.tools[name]
		if !ok {
			continue
		}
		b.WriteString("\t\t{\n")
		fmt.Fprintf(b, "\t\t\tDef: promptr.ToolDef{Name: %q, Description: %q, Params: %s},\n",
			t.Name, t.Description, quote(g.toolParamSchema(t)))
		b.WriteString("\t\t\tInvoke: func(ctx context.Context, argsJSON string) (string, error) {\n")
		fmt.Fprintf(b, "\t\t\t\targs, err := coerce.Into[%sArgs](argsJSON)\n", name)
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn \"\", err\n\t\t\t\t}\n")
		fmt.Fprintf(b, "\t\t\t\tresult, err := tools.%s(ctx, args)\n", name)
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn \"\", err\n\t\t\t\t}\n")
		b.WriteString("\t\t\t\tout, err := json.Marshal(result)\n")
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn \"\", err\n\t\t\t\t}\n")
		b.WriteString("\t\t\t\treturn string(out), nil\n")
		b.WriteString("\t\t\t},\n")
		b.WriteString("\t\t},\n")
	}
	b.WriteString("\t}, options)\n}\n\n")
}

func (g *gen) isUnion(name string) bool {
	_, ok := g.unions[name]
	return ok
}

// renderOptions builds the promptr.Options literal: the default retry budget,
// any binary part params as multimodal UserParts, and — when the return type's
// class graph declares @assert / @check rules — the valx-backed Validate / Check
// closures that finalize applies to each coerced reply.
func (g *gen) renderOptions(partParams []dsl.Param, ret dsl.TypeRef) string {
	fields := []string{"Attempts: 2"}
	if len(partParams) > 0 {
		names := make([]string, len(partParams))
		for i, pm := range partParams {
			names[i] = pm.Name
		}
		fields = append(fields, fmt.Sprintf("UserParts: []promptr.Part{%s}", strings.Join(names, ", ")))
	}
	if g.retHasRules(ret, func(f dsl.FieldDecl) string { return f.Assert }) {
		g.usedValx = true
		fields = append(fields, "Validate: func(v any) error { return valx.Validate(v) }")
	}
	if g.retHasRules(ret, func(f dsl.FieldDecl) string { return f.Check }) {
		g.usedValx = true
		fields = append(fields, `Check: func(v any) error { return valx.ValidateWith(v, "check") }`)
	}
	return "promptr.Options{" + strings.Join(fields, ", ") + "}"
}

// retHasRules reports whether the return type's class graph declares any field
// attribute selected by pick (e.g. @assert or @check), so the generated function
// knows whether to wire the corresponding validation closure.
func (g *gen) retHasRules(t dsl.TypeRef, pick func(dsl.FieldDecl) string) bool {
	return g.typeHasRules(t, pick, map[string]bool{})
}

func (g *gen) typeHasRules(t dsl.TypeRef, pick func(dsl.FieldDecl) string, seen map[string]bool) bool {
	for _, v := range t.Union {
		if g.nameHasRules(v, pick, seen) {
			return true
		}
	}
	if t.Elem != nil && g.typeHasRules(*t.Elem, pick, seen) {
		return true
	}
	return g.nameHasRules(t.Name, pick, seen)
}

func (g *gen) nameHasRules(name string, pick func(dsl.FieldDecl) string, seen map[string]bool) bool {
	if name == "" || seen[name] {
		return false
	}
	seen[name] = true
	if u, ok := g.unions[name]; ok {
		for _, v := range u.Variants {
			if g.nameHasRules(v, pick, seen) {
				return true
			}
		}
		return false
	}
	c := g.classByName(name)
	if c == nil {
		return false
	}
	for _, f := range c.Fields {
		if pick(f) != "" {
			return true
		}
		if g.typeHasRules(f.Type, pick, seen) {
			return true
		}
	}
	return false
}

// isPartType reports whether a DSL type name denotes a multimodal binary input
// that maps to a promptr.Part rather than a templated value.
func isPartType(name string) bool {
	switch name {
	case "image", "audio", "pdf", "file":
		return true
	default:
		return false
	}
}

// unionSamples renders the `Variant{}, ...` zero-value list for promptr.NewUnion.
func unionSamples(u dsl.UnionDecl) string {
	parts := make([]string, len(u.Variants))
	for i, v := range u.Variants {
		parts[i] = v + "{}"
	}
	return strings.Join(parts, ", ")
}

// schemaFor produces the human-readable schema description embedded in the
// prompt — BAML's "show the model the shape you want" technique, which is what
// makes the loose reply coerce reliably.
func (g *gen) schemaFor(t dsl.TypeRef) string {
	if u, ok := g.unions[t.Name]; ok {
		var b strings.Builder
		b.WriteString("Answer with a JSON object matching exactly ONE of these shapes:\n")
		for i, v := range u.Variants {
			if i > 0 {
				b.WriteString("\nOR\n")
			}
			b.WriteString(g.schemaFor(dsl.TypeRef{Name: v}))
		}
		return b.String()
	}
	if c := g.classByName(t.Name); c != nil {
		var b strings.Builder
		b.WriteString("Answer with a JSON object of exactly this shape:\n{\n")
		for _, fld := range c.Fields {
			fmt.Fprintf(&b, "  %q: %s%s%s\n", wireName(fld), g.schemaType(fld.Type), optNote(fld.Type), descNote(fld))
		}
		b.WriteString("}")
		return b.String()
	}
	return "Answer with a single " + g.schemaType(t) + " value."
}

func (g *gen) schemaType(t dsl.TypeRef) string {
	if t.Map {
		return "map<string, " + g.schemaType(*t.Elem) + ">"
	}
	if u, ok := g.unions[t.Name]; ok {
		return "one of {" + strings.Join(u.Variants, " | ") + "}"
	}
	base := t.Name
	if e, ok := g.enums[t.Name]; ok {
		base = "one of [" + strings.Join(e.Members, ", ") + "]"
	}
	if t.List {
		return base + "[]"
	}
	return base
}

// descNote appends a field's @description to its schema line as human guidance.
func descNote(fld dsl.FieldDecl) string {
	if fld.Desc != "" {
		return " // " + fld.Desc
	}
	return ""
}

func optNote(t dsl.TypeRef) string {
	if t.Optional {
		return " (optional)"
	}
	return ""
}

func (g *gen) classByName(name string) *dsl.ClassDecl {
	for i := range g.file.Classes {
		if g.file.Classes[i].Name == name {
			return &g.file.Classes[i]
		}
	}
	return nil
}

// GenerateTests renders the File's `test` blocks into a runnable Go test file
// (package pkg). Each block becomes a Test<Name> that calls the target function
// with the block's args and asserts the `expect` fields of the typed result.
//
// The tests run against a package-level PromptrProvider the developer wires up —
// a deterministic providers/fake or providers/recorded for CI, or a live
// provider — and Skip while it is nil. GenerateTests returns (nil, nil) when the
// File has no test block targeting a plain, assertable function.
func GenerateTests(pkg string, f *dsl.File) ([]byte, error) {
	g := &gen{pkg: pkg, file: f, enums: map[string]dsl.EnumDecl{}, unions: map[string]dsl.UnionDecl{}, tools: map[string]dsl.ToolDecl{}}
	for _, e := range f.Enums {
		g.enums[e.Name] = e
	}
	for _, t := range f.Tools {
		g.tools[t.Name] = t
	}

	var body strings.Builder
	n := 0
	for _, t := range f.Tests {
		fn, ok := funcDecl(f, t.Func)
		if !ok || !testable(fn) {
			continue
		}
		g.renderTest(&body, t, fn)
		n++
	}
	if n == 0 {
		return nil, nil
	}

	var head strings.Builder
	head.WriteString("// Code generated by promptr; DO NOT EDIT.\n\n")
	head.WriteString("package " + pkg + "\n\n")
	head.WriteString("import (\n\t\"context\"\n\t\"testing\"\n\n\t" + quote(runtimePkg) + "\n)\n\n")
	head.WriteString("// PromptrProvider is the Provider the generated promptr tests run against.\n")
	head.WriteString("// Set it (typically in TestMain) to a deterministic provider — providers/fake\n")
	head.WriteString("// or providers/recorded — or a live one. Tests Skip while it is nil.\n")
	head.WriteString("var PromptrProvider promptr.Provider\n\n")

	src := head.String() + body.String()
	out, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("generated test code did not format: %w", err)
	}
	return out, nil
}

// testable reports whether a function can be driven by a generated Go test: it
// must be plain (non-streaming, non-tool) with no binary-part parameters.
func testable(fn dsl.FuncDecl) bool {
	if fn.Stream || len(fn.Tools) > 0 {
		return false
	}
	for _, pm := range fn.Params {
		if isPartType(pm.Type.Name) {
			return false
		}
	}
	return true
}

func funcDecl(f *dsl.File, name string) (dsl.FuncDecl, bool) {
	for _, fn := range f.Funcs {
		if fn.Name == name {
			return fn, true
		}
	}
	return dsl.FuncDecl{}, false
}

func (g *gen) renderTest(b *strings.Builder, t dsl.TestDecl, fn dsl.FuncDecl) {
	fmt.Fprintf(b, "func Test%s(t *testing.T) {\n", goName(t.Name))
	b.WriteString("\tif PromptrProvider == nil {\n\t\tt.Skip(\"promptr: set PromptrProvider to run generated tests\")\n\t}\n")

	args := []string{"context.Background()", "PromptrProvider"}
	for _, pm := range fn.Params {
		args = append(args, g.literal(pm.Type, t.Args[pm.Name]))
	}
	fmt.Fprintf(b, "\tgot, err := %s(%s)\n", fn.Name, strings.Join(args, ", "))
	fmt.Fprintf(b, "\tif err != nil {\n\t\tt.Fatalf(\"%s: %%v\", err)\n\t}\n", fn.Name)

	if len(t.ExpectKeys) == 0 {
		b.WriteString("\t_ = got\n}\n\n")
		return
	}
	cls, _ := classDecl(g.file, fn.Ret.Name)
	ftypes := map[string]dsl.TypeRef{}
	for _, fld := range cls.Fields {
		ftypes[fld.Name] = fld.Type
	}
	for _, k := range t.ExpectKeys {
		field := goName(k)
		lit := g.literal(ftypes[k], t.Expect[k])
		fmt.Fprintf(b, "\tif got.%s != %s {\n", field, lit)
		fmt.Fprintf(b, "\t\tt.Errorf(\"%s = %%v, want %%v\", got.%s, %s)\n\t}\n", k, field, lit)
	}
	b.WriteString("}\n\n")
}

// literal renders a test arg/expect value as a typed Go literal for the field or
// parameter type: strings are quoted, numbers and bools pass through, and an enum
// member becomes its generated const (<Enum><Member>).
func (g *gen) literal(t dsl.TypeRef, val string) string {
	switch t.Name {
	case "string":
		return quote(val)
	case "int", "float", "bool":
		return val
	default:
		if _, isEnum := g.enums[t.Name]; isEnum {
			return t.Name + val
		}
		return quote(val) // defensive: unreachable for validated input
	}
}

func classDecl(f *dsl.File, name string) (dsl.ClassDecl, bool) {
	for _, c := range f.Classes {
		if c.Name == name {
			return c, true
		}
	}
	return dsl.ClassDecl{}, false
}

// goType maps a DSL TypeRef to a Go type expression.
func (g *gen) goType(t dsl.TypeRef) string {
	if t.Map {
		return "map[string]" + g.goType(*t.Elem)
	}
	if len(t.Union) > 0 {
		// An un-named inline union used somewhere other than a function return
		// (e.g. a class field): no generated interface to name, so fall back to
		// any. Named unions (t.Name) flow through primitive below.
		return "any"
	}
	if isPartType(t.Name) {
		return "promptr.Part"
	}
	base := primitive(t.Name)
	switch {
	case t.List:
		return "[]" + base
	case t.Optional:
		return "*" + base
	default:
		return base
	}
}

func primitive(name string) string {
	switch name {
	case "string":
		return "string"
	case "int":
		return "int"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	default:
		return name // a class or enum, used by name
	}
}

// goName converts a snake_case DSL field name to an exported Go field name.
func goName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// quote quotes a Go string literal, preferring raw backticks for multi-line
// content without backticks, falling back to %q.
func quote(s string) string {
	if strings.Contains(s, "\n") && !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}
