package codegen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	. "github.com/smartystreets/goconvey/convey"
	"github.com/zkrebbekx/promptr/dsl"
)

const src = `
enum Severity { LOW HIGH CRITICAL }

class Ticket {
  title    string
  severity Severity
  tags     string[]
  due_days int?
}

client GPT4o { provider "openai" model "gpt-4o" }

function ExtractTicket(text: string) -> Ticket {
  client GPT4o
  prompt #"
    Extract a support ticket.
    {{ ctx.output_schema }}
    Message: {{ text }}
  "#
}
`

func generate(t *testing.T, source string) string {
	f, err := dsl.Parse(source)
	So(err, ShouldBeNil)
	out, err := Generate("tickets", f)
	So(err, ShouldBeNil)
	return string(out)
}

func TestGenerate(t *testing.T) {
	Convey("Given a .promptr file with an enum, class and function", t, func() {
		code := generate(t, src)

		Convey("Then the output is valid, parseable Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})

		Convey("Then the enum becomes a typed const set with CoerceMembers", func() {
			So(code, ShouldContainSubstring, "type Severity string")
			So(code, ShouldContainSubstring, `SeverityCRITICAL Severity = "CRITICAL"`)
			So(code, ShouldContainSubstring, "func (Severity) CoerceMembers() []string")
		})

		Convey("Then the class becomes a struct with json tags, list and pointer", func() {
			So(code, ShouldContainSubstring, "type Ticket struct")
			// gofmt column-aligns fields, so match name/type/tag fragments
			// rather than a fixed-whitespace line.
			So(code, ShouldContainSubstring, "[]string")
			So(code, ShouldContainSubstring, "`json:\"tags\"`")
			So(code, ShouldContainSubstring, "*int")
			So(code, ShouldContainSubstring, "`json:\"due_days,omitempty\"`")
			So(code, ShouldContainSubstring, "`json:\"severity\"`")
		})

		Convey("Then the function has the runtime signature and calls Extract", func() {
			So(code, ShouldContainSubstring, "func ExtractTicket(ctx context.Context, p promptr.Provider, text string) (Ticket, error)")
			So(code, ShouldContainSubstring, "promptr.Extract[Ticket](ctx, p, prompt,")
		})

		Convey("Then the output schema is baked into the prompt", func() {
			So(code, ShouldContainSubstring, "Answer with a JSON object")
			So(code, ShouldContainSubstring, "one of [LOW, HIGH, CRITICAL]")
		})

		Convey("Then the param hole becomes a runtime fmt.Sprint", func() {
			So(code, ShouldContainSubstring, "fmt.Sprint(text)")
		})

		Convey("Then it is gofmt-clean (no double-formatting changes)", func() {
			So(strings.HasPrefix(code, "// Code generated by promptr; DO NOT EDIT."), ShouldBeTrue)
		})
	})
}

func TestGenerateTypesOnlyOmitsRuntimeImports(t *testing.T) {
	Convey("Given a file with only a class (no functions)", t, func() {
		code := generate(t, "class Point { x int y int }")

		Convey("Then no context/promptr import is emitted (would be unused)", func() {
			So(code, ShouldNotContainSubstring, "import")
			So(code, ShouldContainSubstring, "type Point struct")
		})
	})
}

func TestGenerateScalarReturn(t *testing.T) {
	Convey("Given a function returning a bare scalar", t, func() {
		code := generate(t, `function YesNo(q: string) -> bool {
		  client C
		  prompt #"Answer yes or no. {{ ctx.output_schema }} Q: {{ q }}"#
		}`)

		Convey("Then the return type is the Go scalar and schema is the scalar form", func() {
			So(code, ShouldContainSubstring, "(bool, error)")
			So(code, ShouldContainSubstring, "Answer with a single bool value.")
		})
	})
}
