// Package codegen turns a parsed .promptr File into idiomatic Go source.
//
// Each enum becomes a typed-const set with a coerce.Enum method; each class
// becomes a struct with json tags; each function becomes a Go function whose
// body renders the prompt (with the output schema baked in) and calls
// promptr.Extract to get a typed, parse-repaired result. Output is run through
// go/format so it is gofmt-clean and guaranteed to parse.
package codegen

import (
	"fmt"
	"go/format"
	"strings"

	"github.com/zkrebbekx/promptr/dsl"
)

const runtimePkg = "github.com/zkrebbekx/promptr"

// Generate renders the whole File as a single Go source file in package pkg.
func Generate(pkg string, f *dsl.File) ([]byte, error) {
	g := &gen{pkg: pkg, file: f, enums: map[string]dsl.EnumDecl{}}
	for _, e := range f.Enums {
		g.enums[e.Name] = e
	}
	src := g.render()
	out, err := format.Source([]byte(src))
	if err != nil {
		return []byte(src), fmt.Errorf("generated code did not format: %w", err)
	}
	return out, nil
}

type gen struct {
	pkg     string
	file    *dsl.File
	enums   map[string]dsl.EnumDecl
	usedCtx bool
}

func (g *gen) render() string {
	var body strings.Builder
	for _, e := range g.file.Enums {
		g.renderEnum(&body, e)
	}
	for _, c := range g.file.Classes {
		g.renderClass(&body, c)
	}
	for _, c := range g.file.Clients {
		g.renderClient(&body, c)
	}
	for _, fn := range g.file.Funcs {
		g.renderFunc(&body, fn)
	}

	var head strings.Builder
	head.WriteString("// Code generated by promptr; DO NOT EDIT.\n\n")
	head.WriteString("package " + g.pkg + "\n\n")
	if imps := g.imports(); len(imps) > 0 {
		head.WriteString("import (\n")
		for _, imp := range imps {
			head.WriteString("\t" + quote(imp) + "\n")
		}
		head.WriteString(")\n\n")
	}
	return head.String() + body.String()
}

func (g *gen) imports() []string {
	var imps []string
	if g.usedCtx {
		imps = append(imps, "context")
	}
	if len(g.file.Funcs) > 0 || len(g.file.Clients) > 0 {
		imps = append(imps, runtimePkg)
	}
	return imps
}

func (g *gen) renderEnum(b *strings.Builder, e dsl.EnumDecl) {
	fmt.Fprintf(b, "type %s string\n\n", e.Name)
	if len(e.Members) > 0 {
		b.WriteString("const (\n")
		for _, m := range e.Members {
			fmt.Fprintf(b, "\t%s%s %s = %q\n", e.Name, m, e.Name, m)
		}
		b.WriteString(")\n\n")
	}
	fmt.Fprintf(b, "// CoerceMembers lets the coerce kernel fuzzy-match model output to a member.\n")
	fmt.Fprintf(b, "func (%s) CoerceMembers() []string {\n\treturn []string{", e.Name)
	for i, m := range e.Members {
		if i > 0 {
			b.WriteString(", ")
		}
		fmt.Fprintf(b, "%q", m)
	}
	b.WriteString("}\n}\n\n")
}

func (g *gen) renderClass(b *strings.Builder, c dsl.ClassDecl) {
	fmt.Fprintf(b, "type %s struct {\n", c.Name)
	for _, fld := range c.Fields {
		tag := fld.Name
		if fld.Type.Optional {
			tag += ",omitempty"
		}
		fmt.Fprintf(b, "\t%s %s `json:%q`\n", goName(fld.Name), g.goType(fld.Type), tag)
	}
	b.WriteString("}\n\n")
}

// renderClient emits a constructor that resolves a declared client (and its
// reliability policy) from a promptr.Registry. A plain client is just a lookup;
// a policy client wraps the clients it references with Fallback/RoundRobin/Retry
// — composing the wrappers from policy.go.
func (g *gen) renderClient(b *strings.Builder, c dsl.ClientDecl) {
	expr := g.clientBase(c)
	if c.Policy.Retry > 0 {
		expr = fmt.Sprintf("promptr.Retry(%s, %d, 0)", expr, c.Policy.Retry)
	}
	fmt.Fprintf(b, "// Client%s resolves the %q client (with any declared policy) from reg.\n", c.Name, c.Name)
	fmt.Fprintf(b, "func Client%s(reg promptr.Registry) promptr.Provider {\n\treturn %s\n}\n\n", c.Name, expr)
}

func (g *gen) clientBase(c dsl.ClientDecl) string {
	switch {
	case len(c.Policy.Fallback) > 0:
		return "promptr.Fallback(" + clientRefs(c.Policy.Fallback) + ")"
	case len(c.Policy.RoundRobin) > 0:
		return "promptr.RoundRobin(" + clientRefs(c.Policy.RoundRobin) + ")"
	default:
		return fmt.Sprintf("reg.Get(%q)", c.Name)
	}
}

func clientRefs(names []string) string {
	parts := make([]string, len(names))
	for i, n := range names {
		parts[i] = "Client" + n + "(reg)"
	}
	return strings.Join(parts, ", ")
}

func (g *gen) renderFunc(b *strings.Builder, fn dsl.FuncDecl) {
	g.usedCtx = true
	params := []string{"ctx context.Context", "p promptr.Provider"}
	for _, pm := range fn.Params {
		params = append(params, fmt.Sprintf("%s %s", pm.Name, g.goType(pm.Type)))
	}
	ret := g.goType(fn.Ret)
	fmt.Fprintf(b, "func %s(%s) (%s, error) {\n", fn.Name, strings.Join(params, ", "), ret)
	// Render the prompt at runtime so it can use control flow; the output-schema
	// description is still computed at compile time and injected via ctx.
	fmt.Fprintf(b, "\tprompt, err := promptr.Render(%s, map[string]any{\n", quote(fn.Prompt))
	for _, pm := range fn.Params {
		fmt.Fprintf(b, "\t\t%q: %s,\n", pm.Name, pm.Name)
	}
	fmt.Fprintf(b, "\t\t\"ctx\": map[string]any{\"output_schema\": %s},\n", quote(g.schemaFor(fn.Ret)))
	b.WriteString("\t})\n")
	fmt.Fprintf(b, "\tif err != nil {\n\t\tvar zero %s\n\t\treturn zero, err\n\t}\n", ret)
	fmt.Fprintf(b, "\treturn promptr.Extract[%s](ctx, p, prompt, promptr.Options{Attempts: 2})\n}\n\n", ret)
}

// schemaFor produces the human-readable schema description embedded in the
// prompt — BAML's "show the model the shape you want" technique, which is what
// makes the loose reply coerce reliably.
func (g *gen) schemaFor(t dsl.TypeRef) string {
	if c := g.classByName(t.Name); c != nil {
		var b strings.Builder
		b.WriteString("Answer with a JSON object of exactly this shape:\n{\n")
		for _, fld := range c.Fields {
			fmt.Fprintf(&b, "  %q: %s%s\n", fld.Name, g.schemaType(fld.Type), optNote(fld.Type))
		}
		b.WriteString("}")
		return b.String()
	}
	return "Answer with a single " + g.schemaType(t) + " value."
}

func (g *gen) schemaType(t dsl.TypeRef) string {
	base := t.Name
	if e, ok := g.enums[t.Name]; ok {
		base = "one of [" + strings.Join(e.Members, ", ") + "]"
	}
	if t.List {
		return base + "[]"
	}
	return base
}

func optNote(t dsl.TypeRef) string {
	if t.Optional {
		return " (optional)"
	}
	return ""
}

func (g *gen) classByName(name string) *dsl.ClassDecl {
	for i := range g.file.Classes {
		if g.file.Classes[i].Name == name {
			return &g.file.Classes[i]
		}
	}
	return nil
}

// goType maps a DSL TypeRef to a Go type expression.
func (g *gen) goType(t dsl.TypeRef) string {
	base := primitive(t.Name)
	switch {
	case t.List:
		return "[]" + base
	case t.Optional:
		return "*" + base
	default:
		return base
	}
}

func primitive(name string) string {
	switch name {
	case "string":
		return "string"
	case "int":
		return "int"
	case "float":
		return "float64"
	case "bool":
		return "bool"
	default:
		return name // a class or enum, used by name
	}
}

// goName converts a snake_case DSL field name to an exported Go field name.
func goName(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if p == "" {
			continue
		}
		parts[i] = strings.ToUpper(p[:1]) + p[1:]
	}
	return strings.Join(parts, "")
}

// quote quotes a Go string literal, preferring raw backticks for multi-line
// content without backticks, falling back to %q.
func quote(s string) string {
	if strings.Contains(s, "\n") && !strings.Contains(s, "`") {
		return "`" + s + "`"
	}
	return fmt.Sprintf("%q", s)
}
