package codegen

import (
	"go/parser"
	"go/token"
	"strings"
	"testing"

	. "github.com/smartystreets/goconvey/convey"
	"github.com/zkrebbekx/promptr/dsl"
)

const src = `
enum Severity { LOW HIGH CRITICAL }

class Ticket {
  title    string
  severity Severity
  tags     string[]
  due_days int?
}

client GPT4o { provider "openai" model "gpt-4o" }

function ExtractTicket(text: string) -> Ticket {
  client GPT4o
  prompt #"
    Extract a support ticket.
    {{ ctx.output_schema }}
    Message: {{ text }}
  "#
}
`

func generate(_ *testing.T, source string) string {
	f, err := dsl.Parse(source)
	So(err, ShouldBeNil)
	out, err := Generate("tickets", f)
	So(err, ShouldBeNil)
	return string(out)
}

func TestGenerate(t *testing.T) {
	Convey("Given a .promptr file with an enum, class and function", t, func() {
		code := generate(t, src)

		Convey("Then the output is valid, parseable Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})

		Convey("Then the enum becomes a typed const set with CoerceMembers", func() {
			So(code, ShouldContainSubstring, "type Severity string")
			So(code, ShouldContainSubstring, `SeverityCRITICAL Severity = "CRITICAL"`)
			So(code, ShouldContainSubstring, "func (Severity) CoerceMembers() []string")
		})

		Convey("Then the class becomes a struct with json tags, list and pointer", func() {
			So(code, ShouldContainSubstring, "type Ticket struct")
			// gofmt column-aligns fields, so match name/type/tag fragments
			// rather than a fixed-whitespace line.
			So(code, ShouldContainSubstring, "[]string")
			So(code, ShouldContainSubstring, "`json:\"tags\"`")
			So(code, ShouldContainSubstring, "*int")
			So(code, ShouldContainSubstring, "`json:\"due_days,omitempty\"`")
			So(code, ShouldContainSubstring, "`json:\"severity\"`")
		})

		Convey("Then the function has the runtime signature and calls Extract", func() {
			So(code, ShouldContainSubstring, "func ExtractTicket(ctx context.Context, p promptr.Provider, text string) (Ticket, error)")
			So(code, ShouldContainSubstring, "promptr.Extract[Ticket](ctx, p, prompt,")
		})

		Convey("Then the prompt is rendered at runtime with params + ctx schema", func() {
			So(code, ShouldContainSubstring, "promptr.Render(")
			So(code, ShouldContainSubstring, `"text": text,`)
			So(code, ShouldContainSubstring, `"ctx": map[string]any{"output_schema":`)
		})

		Convey("Then the output schema is baked into the injected ctx", func() {
			So(code, ShouldContainSubstring, "Answer with a JSON object")
			So(code, ShouldContainSubstring, "one of [LOW, HIGH, CRITICAL]")
		})

		Convey("Then each client gets a registry-resolving constructor", func() {
			So(code, ShouldContainSubstring, "func ClientGPT4o(reg promptr.Registry) promptr.Provider")
			So(code, ShouldContainSubstring, `reg.Get("GPT4o")`)
		})

		Convey("Then it is gofmt-clean (no double-formatting changes)", func() {
			So(strings.HasPrefix(code, "// Code generated by promptr; DO NOT EDIT."), ShouldBeTrue)
		})
	})
}

func TestGenerateTypesOnlyOmitsRuntimeImports(t *testing.T) {
	Convey("Given a file with only a class (no functions)", t, func() {
		code := generate(t, "class Point { x int y int }")

		Convey("Then no context/promptr import is emitted (would be unused)", func() {
			So(code, ShouldNotContainSubstring, "import")
			So(code, ShouldContainSubstring, "type Point struct")
		})
	})
}

func TestGenerateScalarReturn(t *testing.T) {
	Convey("Given a function returning a bare scalar", t, func() {
		code := generate(t, `function YesNo(q: string) -> bool {
		  client C
		  prompt #"Answer yes or no. {{ ctx.output_schema }} Q: {{ q }}"#
		}`)

		Convey("Then the return type is the Go scalar and schema is the scalar form", func() {
			So(code, ShouldContainSubstring, "(bool, error)")
			So(code, ShouldContainSubstring, "Answer with a single bool value.")
		})
	})
}

func TestGenerateClientPolicies(t *testing.T) {
	Convey("Given clients composed with fallback and retry", t, func() {
		code := generate(t, `
client Fast { provider "openai" model "gpt-4o-mini" }
client Smart { provider "anthropic" model "claude-opus-4-8" }
client Reliable {
  fallback [Smart, Fast]
  retry 3
}`)

		Convey("Then plain clients become registry lookups", func() {
			So(code, ShouldContainSubstring, "func ClientFast(reg promptr.Registry) promptr.Provider")
			So(code, ShouldContainSubstring, `reg.Get("Fast")`)
		})

		Convey("Then the policy client wraps referenced clients with Fallback+Retry", func() {
			So(code, ShouldContainSubstring, "promptr.Retry(promptr.Fallback(ClientSmart(reg), ClientFast(reg)), 3, 0)")
		})

		Convey("Then the generated code is valid Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})
	})
}

func TestGenerateUnions(t *testing.T) {
	Convey("Given named + inline unions over classes", t, func() {
		code := generate(t, `
class Search { query string }
class Escalate { reason string }
union Action = Search | Escalate
function Route(msg: string) -> Action {
  client C
  prompt #"Route it. {{ ctx.output_schema }} msg: {{ msg }}"#
}`)

		Convey("Then a sealed interface + variant markers are emitted", func() {
			So(code, ShouldContainSubstring, "type Action interface{ isAction() }")
			So(code, ShouldContainSubstring, "func (Search) isAction()")
			So(code, ShouldContainSubstring, "func (Escalate) isAction()")
		})

		Convey("Then the function returns the interface via ExtractUnion", func() {
			So(code, ShouldContainSubstring, "func Route(ctx context.Context, p promptr.Provider, msg string) (Action, error)")
			So(code, ShouldContainSubstring, "promptr.ExtractUnion[Action](ctx, p, prompt, promptr.Options{Attempts: 2}, promptr.NewUnion(Search{}, Escalate{}))")
		})

		Convey("Then the baked schema shows the model the ONE-of choice", func() {
			So(code, ShouldContainSubstring, "matching exactly ONE of these shapes")
		})

		Convey("Then the output is valid Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})
	})
}

func TestGenerateInlineUnionReturn(t *testing.T) {
	Convey("Given an inline union return type", t, func() {
		code := generate(t, `
class Reply { text string }
class Handoff { team string }
function Triage(q: string) -> Reply | Handoff {
  client C
  prompt #"{{ q }} {{ ctx.output_schema }}"#
}`)

		Convey("Then a synthesized <Func>Result interface is used", func() {
			So(code, ShouldContainSubstring, "type TriageResult interface{ isTriageResult() }")
			So(code, ShouldContainSubstring, "(TriageResult, error)")
			So(code, ShouldContainSubstring, "promptr.NewUnion(Reply{}, Handoff{})")
		})
	})
}

func TestGenerateMapAndAttrs(t *testing.T) {
	Convey("Given a map field and @description/@alias attributes", t, func() {
		code := generate(t, `
class Profile {
  scores map<string, int>
  name   string @description("full legal name") @alias("full_name")
}`)

		Convey("Then the map becomes a Go map type", func() {
			So(code, ShouldContainSubstring, "map[string]int")
		})

		Convey("Then @alias drives the json tag", func() {
			So(code, ShouldContainSubstring, "`json:\"full_name\"`")
		})

		Convey("Then it is valid Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})
	})
}

func TestGenerateStreamAndMultimodal(t *testing.T) {
	Convey("Given a streaming function with an image param", t, func() {
		code := generate(t, `
class Caption { text string }
function Describe(photo: image, hint: string) -> stream Caption {
  client C
  prompt #"Describe it. {{ hint }} {{ ctx.output_schema }}"#
}`)

		Convey("Then the image param is a promptr.Part", func() {
			So(code, ShouldContainSubstring, "photo promptr.Part")
		})

		Convey("Then the return is a channel of partials via ExtractStream", func() {
			So(code, ShouldContainSubstring, "(<-chan promptr.Partial[Caption], error)")
			So(code, ShouldContainSubstring, "promptr.ExtractStream[Caption](ctx, p, prompt,")
		})

		Convey("Then the part param is attached as a multimodal UserPart, not templated", func() {
			So(code, ShouldContainSubstring, "UserParts: []promptr.Part{photo}")
			So(code, ShouldNotContainSubstring, `"photo": photo`)
		})

		Convey("Then it is valid Go", func() {
			_, err := parser.ParseFile(token.NewFileSet(), "gen.go", code, parser.AllErrors)
			So(err, ShouldBeNil)
		})
	})
}
