// Code generated by promptr; DO NOT EDIT.

package ticket

import (
	"context"
	"fmt"
	"github.com/zkrebbekx/promptr"
)

type Severity string

const (
	SeverityLOW      Severity = "LOW"
	SeverityHIGH     Severity = "HIGH"
	SeverityCRITICAL Severity = "CRITICAL"
)

// CoerceMembers lets the coerce kernel fuzzy-match model output to a member.
func (Severity) CoerceMembers() []string {
	return []string{"LOW", "HIGH", "CRITICAL"}
}

type Ticket struct {
	Title    string   `json:"title"`
	Severity Severity `json:"severity"`
	Tags     []string `json:"tags"`
	DueDays  *int     `json:"due_days,omitempty"`
}

func ExtractTicket(ctx context.Context, p promptr.Provider, text string) (Ticket, error) {
	prompt := `
    Extract a support ticket from the user's message.
    ` + `Answer with a JSON object of exactly this shape:
{
  "title": string
  "severity": one of [LOW, HIGH, CRITICAL]
  "tags": string[]
  "due_days": int (optional)
}` + `
    Message: ` + fmt.Sprint(text) + `
  `
	return promptr.Extract[Ticket](ctx, p, prompt, promptr.Options{Attempts: 2})
}
