// Code generated by promptr; DO NOT EDIT.

package ticket

import (
	"context"
	"github.com/zkrebbekx/promptr"
)

type Severity string

const (
	SeverityLOW      Severity = "LOW"
	SeverityHIGH     Severity = "HIGH"
	SeverityCRITICAL Severity = "CRITICAL"
)

// CoerceMembers lets the coerce kernel fuzzy-match model output to a member.
func (Severity) CoerceMembers() []string {
	return []string{"LOW", "HIGH", "CRITICAL"}
}

type Ticket struct {
	Title    string   `json:"title"`
	Severity Severity `json:"severity"`
	Tags     []string `json:"tags"`
	DueDays  *int     `json:"due_days,omitempty"`
}

// ClientDefault resolves the "Default" client (with any declared policy) from reg.
func ClientDefault(reg promptr.Registry) promptr.Provider {
	return reg.Get("Default")
}

func ExtractTicket(ctx context.Context, p promptr.Provider, text string, opt ...promptr.Option) (Ticket, error) {
	prompt, err := promptr.Render(`
    Extract a support ticket from the user's message.
    {{ ctx.output_schema }}
    Message: {{ text }}
  `, map[string]any{
		"text": text,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "title": string
  "severity": one of [LOW, HIGH, CRITICAL]
  "tags": string[]
  "due_days": int (optional)
}`},
	})
	if err != nil {
		var zero Ticket
		return zero, err
	}
	options := promptr.Options{Attempts: 2}
	for _, o := range opt {
		o(&options)
	}
	return promptr.Extract[Ticket](ctx, p, prompt, options)
}
