// Code generated by promptr; DO NOT EDIT.

package multiagent

import (
	"context"
	"encoding/json"
	"github.com/zkrebbekx/promptr"
	"github.com/zkrebbekx/promptr/coerce"
)

type Research struct {
	Summary string   `json:"summary"`
	Sources []string `json:"sources"`
}

type Brief struct {
	Topic          string `json:"topic"`
	Recommendation string `json:"recommendation"`
}

// ClientDefault resolves the "Default" client (with any declared policy) from reg.
func ClientDefault(reg promptr.Registry) promptr.Provider {
	return reg.Get("Default")
}

// ResearchTopicArgs are the typed arguments for the "ResearchTopic" sub-agent.
type ResearchTopicArgs struct {
	Topic string `json:"topic"`
}

func ResearchTopic(ctx context.Context, p promptr.Provider, topic string, opt ...promptr.Option) (Research, error) {
	prompt, err := promptr.Render(`
    Research the topic and summarize what you find.
    {{ ctx.output_schema }}
    Topic: {{ topic }}
  `, map[string]any{
		"topic": topic,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "summary": string
  "sources": string[]
}`},
	})
	if err != nil {
		var zero Research
		return zero, err
	}
	options := promptr.Options{Attempts: 2}
	for _, o := range opt {
		o(&options)
	}
	return promptr.Extract[Research](ctx, p, prompt, options)
}

func WriteBrief(ctx context.Context, p promptr.Provider, request string, opt ...promptr.Option) (Brief, error) {
	prompt, err := promptr.Render(`
    Write a decision brief for the request. Use the ResearchTopic sub-agent to
    gather background before recommending.
    {{ ctx.output_schema }}
    Request: {{ request }}
  `, map[string]any{
		"request": request,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object of exactly this shape:
{
  "topic": string
  "recommendation": string
}`},
	})
	if err != nil {
		var zero Brief
		return zero, err
	}
	options := promptr.Options{Attempts: 2}
	for _, o := range opt {
		o(&options)
	}
	return promptr.RunTools[Brief](ctx, p, prompt, []promptr.Tool{
		{
			Def: promptr.ToolDef{Name: "ResearchTopic", Description: "Research a topic and return a short summary with sources.", Params: `A JSON object with:
{
  "topic": string
}`},
			Invoke: func(ctx context.Context, argsJSON string) (string, error) {
				args, err := coerce.Into[ResearchTopicArgs](argsJSON)
				if err != nil {
					return "", err
				}
				result, err := ResearchTopic(ctx, p, args.Topic, opt...)
				if err != nil {
					return "", err
				}
				out, err := json.Marshal(result)
				if err != nil {
					return "", err
				}
				return string(out), nil
			},
		},
	}, options)
}
