// Code generated by promptr; DO NOT EDIT.

package route

import (
	"context"
	"github.com/zkrebbekx/promptr"
)

type Search struct {
	Query string `json:"query"`
	Topk  int    `json:"max_results"`
}

type Escalate struct {
	Reason   string            `json:"reason"`
	Metadata map[string]string `json:"metadata"`
}

// Action is a sealed union: one of Search, Escalate.
type Action interface{ isAction() }

func (Search) isAction()   {}
func (Escalate) isAction() {}

// ClientDefault resolves the "Default" client (with any declared policy) from reg.
func ClientDefault(reg promptr.Registry) promptr.Provider {
	return reg.Get("Default")
}

func Route(ctx context.Context, p promptr.Provider, message string) (Action, error) {
	prompt, err := promptr.Render(`
    Decide how to handle the user's message: either run a Search or Escalate it.
    {{ ctx.output_schema }}
    Message: {{ message }}
  `, map[string]any{
		"message": message,
		"ctx": map[string]any{"output_schema": `Answer with a JSON object matching exactly ONE of these shapes:
Answer with a JSON object of exactly this shape:
{
  "query": string // the search terms to look up
  "max_results": int
}
OR
Answer with a JSON object of exactly this shape:
{
  "reason": string // why this needs a human
  "metadata": map<string, string>
}`},
	})
	if err != nil {
		var zero Action
		return zero, err
	}
	return promptr.ExtractUnion[Action](ctx, p, prompt, promptr.Options{Attempts: 2}, promptr.NewUnion(Search{}, Escalate{}))
}
